In [47]:
import pandas as pd
from pathlib import Path

In [48]:
# Import the CSV file
census_data_csv = Path("Data/censusdata.csv")
census_data_df = pd.read_csv(census_data_csv, encoding='latin-1')

In [49]:
census_data_df.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       ...
       'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013', 'RNETMIG2014',
       'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017', 'RNETMIG2018',
       'RNETMIG2019', 'RNETMIG2020'],
      dtype='object', length=180)

In [50]:
# Create a new dataframe with columns E, F, G, J through T, which shows the total population for each state 
# and county based on the following formula: Population base + Birth - deaths + Migration 
census_df = census_data_df.loc[:, ['COUNTY', 'STNAME', 'CTYNAME', 'POPESTIMATE2010', 'POPESTIMATE2011', \
                                   'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015', \
                                   'POPESTIMATE2016', 'POPESTIMATE2017', 'POPESTIMATE2018', 'POPESTIMATE2019', \
                                   'POPESTIMATE2020']]
census_df.head()

,COUNTY,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
0,0,Alabama,Alabama,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
1,1,Alabama,Autauga County,54761,55229,54970,54747,54922,54903,55302,55448,55533,55769,56145
2,3,Alabama,Baldwin County,183121,186579,190203,194978,199306,203101,207787,212737,218071,223565,229287
3,5,Alabama,Barbour County,27325,27344,27172,26946,26768,26300,25828,25169,24887,24657,24589
4,7,Alabama,Bibb County,22858,22736,22657,22510,22541,22553,22590,22532,22300,22313,22136

# State analysis

In [51]:
# Create another dataframe with rows that have "0" in column E, which only looks at the states (no counties)
state_df = census_df[census_df['COUNTY'] == 0]
state_df.head()

,COUNTY,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
0,0,Alabama,Alabama,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
68,0,Alaska,Alaska,713982,722349,730810,737626,737075,738430,742575,740983,736624,733603,731158
99,0,Arizona,Arizona,6407342,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7421401
115,0,Arkansas,Arkansas,2921998,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3030522
191,0,California,California,37319550,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39368078

In [52]:
#convert strings to numeric type for calculation of %
state_df.loc[:,['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', \
                 'POPESTIMATE2014', 'POPESTIMATE2015', 'POPESTIMATE2016', 'POPESTIMATE2017', \
                 'POPESTIMATE2018', 'POPESTIMATE2019', 'POPESTIMATE2020']] = \
state_df.loc[:,['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', \
                 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015', \
                 'POPESTIMATE2016', 'POPESTIMATE2017', 'POPESTIMATE2018', \
                 'POPESTIMATE2019', 'POPESTIMATE2020']].apply(pd.to_numeric)

state_df.dtypes

COUNTY              int64
STNAME             object
CTYNAME            object
POPESTIMATE2010     int64
POPESTIMATE2011     int64
POPESTIMATE2012     int64
POPESTIMATE2013     int64
POPESTIMATE2014     int64
POPESTIMATE2015     int64
POPESTIMATE2016     int64
POPESTIMATE2017     int64
POPESTIMATE2018     int64
POPESTIMATE2019     int64
POPESTIMATE2020     int64
dtype: object

In [53]:
state_df.head()

,COUNTY,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
0,0,Alabama,Alabama,4785514,4799642,4816632,4831586,4843737,4854803,4866824,4877989,4891628,4907965,4921532
68,0,Alaska,Alaska,713982,722349,730810,737626,737075,738430,742575,740983,736624,733603,731158
99,0,Arizona,Arizona,6407342,6473416,6556344,6634690,6732873,6832810,6944767,7048088,7164228,7291843,7421401
115,0,Arkansas,Arkansas,2921998,2941038,2952876,2960459,2968759,2979732,2991815,3003855,3012161,3020985,3030522
191,0,California,California,37319550,37636311,37944551,38253768,38586706,38904296,39149186,39337785,39437463,39437610,39368078

In [54]:
states_raw_df = state_df.drop('COUNTY', axis=1)
states_raw_df.reset_index()
selected_states = ['District of Columbia', 'Utah', 'Texas', 'Illinois', 'West Virginia']
select_states_population_df = states_raw_df.groupby("STNAME").sum() 
select_states_population_df
select_states_total_population_df = select_states_population_df[select_states_population_df.index.isin(selected_states)]
select_states_total_population_df

,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
STNAME,,,,,,,,,,,,
District of Columbia,District of Columbia,605282,620290,635737,651559,663603,677014,687576,697079,704147,708253,712816
Illinois,Illinois,12840545,12867783,12883029,12895778,12885092,12859585,12821709,12779893,12724685,12667017,12587530
Texas,Texas,25241897,25645504,26084120,26479646,26963092,27468531,27914064,28291024,28624564,28986794,29360759
Utah,Utah,2775413,2814797,2854146,2898773,2938327,2983626,3044241,3103540,3155153,3203383,3249879
West Virginia,West Virginia,1854265,1856606,1857446,1854768,1850569,1843332,1832435,1818683,1805953,1795263,1784787

In [55]:
# storing the dataframe to access it from another jupiter notebook
%store select_states_total_population_df

Stored 'select_states_total_population_df' (DataFrame)

In [56]:
state_df.loc[:,["Popestimate Yearly Change 2011(%)"]] = ((state_df["POPESTIMATE2011"] / \
                                        state_df["POPESTIMATE2010"])-1)*100

state_df.loc[:,["Popestimate Yearly Change 2012(%)"]] = ((state_df["POPESTIMATE2012"] / \
                                        state_df["POPESTIMATE2011"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2013(%)"]] = ((state_df["POPESTIMATE2013"] / \
                                        state_df["POPESTIMATE2012"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2014(%)"]] = ((state_df["POPESTIMATE2014"] / \
                                        state_df["POPESTIMATE2013"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2015(%)"]] = ((state_df["POPESTIMATE2015"] / \
                                        state_df["POPESTIMATE2014"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2016(%)"]] = ((state_df["POPESTIMATE2016"] / \
                                        state_df["POPESTIMATE2015"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2017(%)"]] = ((state_df["POPESTIMATE2017"] / \
                                        state_df["POPESTIMATE2016"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2018(%)"]] = ((state_df["POPESTIMATE2018"] / \
                                        state_df["POPESTIMATE2017"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2019(%)"]] = ((state_df["POPESTIMATE2019"] / \
                                        state_df["POPESTIMATE2018"])-1)*100
state_df.loc[:,["Popestimate Yearly Change 2020(%)"]] = ((state_df["POPESTIMATE2020"] / \
                                        state_df["POPESTIMATE2019"])-1)*100
state_df.loc[:,["Popestimate 10-Year Change 2020(%)"]] = ((state_df["POPESTIMATE2020"] / \
                                        state_df["POPESTIMATE2010"])-1)*100

In [57]:
state_pct_change_df = state_df.loc[:, ['STNAME','CTYNAME', 'Popestimate Yearly Change 2011(%)', \
                                             'Popestimate Yearly Change 2012(%)', \
                                             'Popestimate Yearly Change 2013(%)', \
                                             'Popestimate Yearly Change 2014(%)',
                                             'Popestimate Yearly Change 2015(%)',
                                             'Popestimate Yearly Change 2016(%)',
                                             'Popestimate Yearly Change 2017(%)',
                                             'Popestimate Yearly Change 2018(%)',
                                             'Popestimate Yearly Change 2019(%)',
                                             'Popestimate Yearly Change 2020(%)',
                                             'Popestimate 10-Year Change 2020(%)']]
state_pct_change_df.head()

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
0,Alabama,Alabama,0.295224,0.353985,0.310466,0.251491,0.228460,0.247610,0.229410,0.279603,0.333979,0.276428,2.842286
68,Alaska,Alaska,1.171878,1.171317,0.932664,-0.074699,0.183835,0.561326,-0.214389,-0.588273,-0.410114,-0.333287,2.405663
99,Arizona,Arizona,1.031223,1.281055,1.194965,1.479843,1.484314,1.638521,1.487753,1.647823,1.781281,1.776752,15.826516
115,Arkansas,Arkansas,0.651609,0.402511,0.256800,0.280362,0.369616,0.405506,0.402431,0.276511,0.292946,0.315692,3.714034
191,California,California,0.848780,0.818996,0.814918,0.870340,0.823055,0.629468,0.481744,0.253390,0.000373,-0.176309,5.489155

In [58]:
# Sort the data by 10-Year Change by State, Highest to Lowest
state_sorted_df = state_pct_change_df.sort_values(["Popestimate 10-Year Change 2020(%)"],
                                           ascending=False)

# Reset Index
state_sorted_df = state_sorted_df.reset_index(drop=True)
state_sorted_df.head()

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
0,District of Columbia,District of Columbia,2.479505,2.490287,2.488765,1.848490,2.020937,1.560086,1.382102,1.013945,0.583117,0.644261,17.765934
1,Utah,Utah,1.419032,1.397934,1.563585,1.364508,1.541660,2.031588,1.947908,1.663036,1.528610,1.451466,17.095330
2,Texas,Texas,1.598957,1.710304,1.516348,1.825727,1.874559,1.621976,1.350430,1.178961,1.265452,1.290122,16.317561
3,Idaho,Idaho,0.856432,0.734596,1.011523,1.252750,1.240437,1.908690,2.120442,1.879872,2.110984,2.115804,16.303215
4,Nevada,Nevada,0.393379,1.163092,1.176316,1.511691,1.759388,1.778750,1.799658,1.972614,1.981242,1.536445,16.125023

In [59]:
state_sorted_df

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
0,District of Columbia,District of Columbia,2.479505,2.490287,2.488765,1.848490,2.020937,1.560086,1.382102,1.013945,0.583117,0.644261,17.765934
1,Utah,Utah,1.419032,1.397934,1.563585,1.364508,1.541660,2.031588,1.947908,1.663036,1.528610,1.451466,17.095330
2,Texas,Texas,1.598957,1.710304,1.516348,1.825727,1.874559,1.621976,1.350430,1.178961,1.265452,1.290122,16.317561
3,Idaho,Idaho,0.856432,0.734596,1.011523,1.252750,1.240437,1.908690,2.120442,1.879872,2.110984,2.115804,16.303215
4,Nevada,Nevada,0.393379,1.163092,1.176316,1.511691,1.759388,1.778750,1.799658,1.972614,1.981242,1.536445,16.125023
5,Arizona,Arizona,1.031223,1.281055,1.194965,1.479843,1.484314,1.638521,1.487753,1.647823,1.781281,1.776752,15.826516
6,Florida,Florida,1.111442,1.293105,1.293450,1.545658,1.839595,2.018516,1.696068,1.324478,1.115647,1.122536,15.319681
7,Colorado,Colorado,1.473213,1.401043,1.484772,1.553149,1.899830,1.641192,1.327184,1.419406,1.076520,0.854964,15.060409
8,Washington,Washington,1.252705,1.041673,0.980677,1.310303,1.555161,1.851105,1.753297,1.330677,1.158940,1.045282,14.097608
9,North Dakota,North Dakota,1.596735,2.436231,2.979378,2.155434,2.274290,0.076370,0.084776,0.436997,0.481803,0.207536,13.420783
10,South Carolina,South Carolina,0.794008,0.992412,1.005334,1.266955,1.432568,1.368973,1.290965,1.285035,1.296227,1.169862,12.558528
11,North Carolina,North Carolina,0.880738,0.961775,0.973224,0.919880,1.005535,1.241220,1.121415,1.124978,1.058822,0.946913,10.718343
12,Oregon,Oregon,0.913536,0.708296,0.615574,1.053411,1.338941,1.859605,1.319800,0.873919,0.778719,0.602237,10.524586
13,Georgia,Georgia,0.941300,1.019520,0.727131,0.958459,1.113561,1.228368,1.053399,0.982602,1.032674,0.771517,10.273749
14,Delaware,Delaware,0.882902,0.873522,0.933242,0.981428,0.957422,0.841131,0.837168,0.944003,1.001360,1.038326,9.688467
15,South Dakota,South Dakota,0.924659,1.228422,1.066367,0.821002,0.587640,1.056557,1.162334,0.647109,0.880273,0.630124,9.375724
16,Montana,Montana,0.685151,0.666655,0.994853,0.838035,0.864219,1.031706,1.125092,0.754938,0.782149,0.976897,9.068767
17,Tennessee,Tennessee,0.704585,0.866428,0.638051,0.733791,0.775248,0.847915,0.954268,0.944667,0.769307,0.827325,8.359917
18,Virginia,Virginia,0.977480,1.049302,0.835485,0.721536,0.623816,0.601723,0.633906,0.471124,0.537216,0.396429,7.060802
19,Minnesota,Minnesota,0.671935,0.577561,0.692180,0.700738,0.574710,0.754157,0.794935,0.708870,0.557895,0.306540,6.522544
20,Nebraska,Nebraska,0.618881,0.694057,0.653939,0.757954,0.643845,0.762344,0.551539,0.444132,0.366604,0.257740,5.900827
21,Oklahoma,Oklahoma,0.766221,0.804894,0.905161,0.656376,0.807669,0.450708,0.138972,0.251322,0.435858,0.507666,5.871494
22,California,California,0.848780,0.818996,0.814918,0.870340,0.823055,0.629468,0.481744,0.253390,0.000373,-0.176309,5.489155
23,Massachusetts,Massachusetts,0.727609,0.756718,0.763610,0.740206,0.482197,0.438339,0.531398,0.322865,0.133073,-0.018985,4.981908
24,Maryland,Maryland,0.888909,0.824178,0.625334,0.588453,0.477579,0.308690,0.352455,0.231695,0.211862,0.014005,4.612679
25,Indiana,Indiana,0.411290,0.333561,0.483041,0.387242,0.233823,0.400155,0.364121,0.546572,0.485618,0.355712,4.073581
26,New Hampshire,New Hampshire,0.276198,0.320574,0.195897,0.526267,0.241558,0.464605,0.498700,0.345751,0.422046,0.403591,3.756663
27,Arkansas,Arkansas,0.651609,0.402511,0.256800,0.280362,0.369616,0.405506,0.402431,0.276511,0.292946,0.315692,3.714034
28,Iowa,Iowa,0.522909,0.328424,0.555472,0.540024,0.382493,0.341677,0.335886,0.196136,0.307819,0.125491,3.695467
29,Hawaii,Hawaii,1.140612,1.133476,0.976420,0.462301,0.541497,0.413633,-0.218492,-0.186637,-0.526104,-0.608146,3.152630
30,Wyoming,Wyoming,0.524329,1.615004,1.034239,0.092513,0.553880,-0.195433,-0.896892,-0.162071,0.183403,0.381303,3.152528
31,Kentucky,Kentucky,0.514044,0.390041,0.433947,0.228868,0.274712,0.252420,0.344211,0.194879,0.180813,0.109696,2.961666
32,Alabama,Alabama,0.295224,0.353985,0.310466,0.251491,0.228460,0.247610,0.229410,0.279603,0.333979,0.276428,2.842286
33,Missouri,Missouri,0.251714,0.246956,0.281479,0.267103,0.268702,0.262912,0.328300,0.238964,0.236517,0.180328,2.592673
34,Wisconsin,Wisconsin,0.268903,0.262626,0.300429,0.264674,0.169089,0.212444,0.311281,0.279157,0.262716,0.138619,2.497426
35,Alaska,Alaska,1.171878,1.171317,0.932664,-0.074699,0.183835,0.561326,-0.214389,-0.588273,-0.410114,-0.333287,2.405663
36,Louisiana,Louisiana,0.695523,0.564284,0.520918,0.430130,0.453299,0.307435,-0.163906,-0.197339,-0.132170,-0.278364,2.215425
37,New Mexico,New Mexico,0.779468,0.336809,0.245148,-0.124090,-0.007894,0.118848,0.013811,0.043482,0.280835,0.318389,2.019990
38,Kansas,Kansas,0.399228,0.569646,0.286969,0.261030,0.305183,0.077644,-0.071576,0.063761,-0.003879,0.040170,1.943101
39,Maine,Maine,0.061914,-0.028529,0.033808,0.201273,-0.159178,0.244527,0.254813,0.327907,0.421379,0.324795,1.693969
40,Ohio,Ohio,0.054474,0.045350,0.248646,0.232139,0.135630,0.152680,0.220325,0.130176,0.133680,-0.028128,1.332542
41,New Jersey,New Jersey,0.330714,0.193905,0.137355,0.106753,0.034227,0.036887,0.164116,0.040312,-0.005308,-0.099952,0.942332
42,Michigan,Michigan,0.055236,0.154163,0.166827,0.173791,0.024668,0.197635,0.227393,0.105585,-0.024942,-0.182678,0.900604
43,Pennsylvania,Pennsylvania,0.280425,0.173146,0.081564,0.100583,-0.019965,-0.010712,0.048567,0.112766,-0.079818,-0.122112,0.565225
44,Rhode Island,Rhode Island,-0.015655,0.100965,0.063229,0.090094,0.035494,0.087994,-0.119302,0.263498,-0.111390,-0.097622,0.297061
45,Mississippi,Mississippi,0.287213,0.183005,0.175568,0.068666,-0.055517,0.012173,0.002642,-0.260644,-0.155957,-0.384155,-0.128896
46,New York,New York,0.515285,0.381750,0.266297,0.137279,0.019793,-0.106474,-0.216649,-0.253911,-0.414279,-0.649202,-0.325671
47,Vermont,Vermont,0.209463,-0.133291,0.038636,-0.145228,0.018699,-0.230741,0.122684,-0.052789,-0.120998,-0.112011,-0.405665
48,Connecticut,Connecticut,0.264279,0.183329,0.016160,-0.002642,-0.198459,-0.243301,-0.125872,-0.021341,-0.238882,-0.252831,-0.619333
49,Illinois,Illinois,0.212125,0.118482,0.098960,-0.082864,-0.197957,-0.294535,-0.326134,-0.431991,-0.453198,-0.627512,-1.970438
50,West Virginia,West Virginia,0.126249,0.045244,-0.144176,-0.226389,-0.391069,-0.591158,-0.750477,-0.699957,-0.591931,-0.583536,-3.746929

In [60]:
# Print out the data for the state or territory with the highest 10-Year Change
highest_10y_change = state_sorted_df.loc[0, :]
highest_10y_change

STNAME                                District of Columbia
CTYNAME                               District of Columbia
Popestimate Yearly Change 2011(%)                 2.479505
Popestimate Yearly Change 2012(%)                 2.490287
Popestimate Yearly Change 2013(%)                 2.488765
Popestimate Yearly Change 2014(%)                  1.84849
Popestimate Yearly Change 2015(%)                 2.020937
Popestimate Yearly Change 2016(%)                 1.560086
Popestimate Yearly Change 2017(%)                 1.382102
Popestimate Yearly Change 2018(%)                 1.013945
Popestimate Yearly Change 2019(%)                 0.583117
Popestimate Yearly Change 2020(%)                 0.644261
Popestimate 10-Year Change 2020(%)               17.765934
Name: 0, dtype: object

In [61]:
# Print out the data for the state or territory with the second highest 10-Year Change
highest_10y_change = state_sorted_df.loc[1, :]
highest_10y_change

STNAME                                    Utah
CTYNAME                                   Utah
Popestimate Yearly Change 2011(%)     1.419032
Popestimate Yearly Change 2012(%)     1.397934
Popestimate Yearly Change 2013(%)     1.563585
Popestimate Yearly Change 2014(%)     1.364508
Popestimate Yearly Change 2015(%)      1.54166
Popestimate Yearly Change 2016(%)     2.031588
Popestimate Yearly Change 2017(%)     1.947908
Popestimate Yearly Change 2018(%)     1.663036
Popestimate Yearly Change 2019(%)      1.52861
Popestimate Yearly Change 2020(%)     1.451466
Popestimate 10-Year Change 2020(%)    17.09533
Name: 1, dtype: object

In [62]:
# Print out the data for the state or territory with the lowest 10-Year Change
lowest_10y_change = state_sorted_df.loc[len(state_sorted_df)-1, :]
lowest_10y_change

STNAME                                West Virginia
CTYNAME                               West Virginia
Popestimate Yearly Change 2011(%)          0.126249
Popestimate Yearly Change 2012(%)          0.045244
Popestimate Yearly Change 2013(%)         -0.144176
Popestimate Yearly Change 2014(%)         -0.226389
Popestimate Yearly Change 2015(%)         -0.391069
Popestimate Yearly Change 2016(%)         -0.591158
Popestimate Yearly Change 2017(%)         -0.750477
Popestimate Yearly Change 2018(%)         -0.699957
Popestimate Yearly Change 2019(%)         -0.591931
Popestimate Yearly Change 2020(%)         -0.583536
Popestimate 10-Year Change 2020(%)        -3.746929
Name: 50, dtype: object

In [63]:
# Print out the data for the state or territory with the second lowest 10-Year Change
lowest_10y_change = state_sorted_df.loc[len(state_sorted_df)-2, :]
lowest_10y_change

STNAME                                Illinois
CTYNAME                               Illinois
Popestimate Yearly Change 2011(%)     0.212125
Popestimate Yearly Change 2012(%)     0.118482
Popestimate Yearly Change 2013(%)      0.09896
Popestimate Yearly Change 2014(%)    -0.082864
Popestimate Yearly Change 2015(%)    -0.197957
Popestimate Yearly Change 2016(%)    -0.294535
Popestimate Yearly Change 2017(%)    -0.326134
Popestimate Yearly Change 2018(%)    -0.431991
Popestimate Yearly Change 2019(%)    -0.453198
Popestimate Yearly Change 2020(%)    -0.627512
Popestimate 10-Year Change 2020(%)   -1.970438
Name: 49, dtype: object

In [64]:
#Create a dataframe with only Washington (District of Columbia), Utah, Texas, Illinois, Virginia states
# Select the first 3 rows
first_3_rows = state_sorted_df.iloc[:3]

# Select the last 2 rows
last_2_rows = state_sorted_df.iloc[-2:]

# Concatenate the selected rows into a new DataFrame
select_states_population_change_df = pd.concat([first_3_rows, last_2_rows])
select_states_population_change_df

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
0,District of Columbia,District of Columbia,2.479505,2.490287,2.488765,1.848490,2.020937,1.560086,1.382102,1.013945,0.583117,0.644261,17.765934
1,Utah,Utah,1.419032,1.397934,1.563585,1.364508,1.541660,2.031588,1.947908,1.663036,1.528610,1.451466,17.095330
2,Texas,Texas,1.598957,1.710304,1.516348,1.825727,1.874559,1.621976,1.350430,1.178961,1.265452,1.290122,16.317561
49,Illinois,Illinois,0.212125,0.118482,0.098960,-0.082864,-0.197957,-0.294535,-0.326134,-0.431991,-0.453198,-0.627512,-1.970438
50,West Virginia,West Virginia,0.126249,0.045244,-0.144176,-0.226389,-0.391069,-0.591158,-0.750477,-0.699957,-0.591931,-0.583536,-3.746929

In [65]:
# storing the dataframe to access it from another jupiter notebook
%store select_states_population_change_df

Stored 'select_states_population_change_df' (DataFrame)

# County analysis

In [66]:
# Create another dataframe, which only looks at the counties
county_df = census_df[census_df['COUNTY'] != 0]
county_df

,COUNTY,STNAME,CTYNAME,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020
1,1,Alabama,Autauga County,54761,55229,54970,54747,54922,54903,55302,55448,55533,55769,56145
2,3,Alabama,Baldwin County,183121,186579,190203,194978,199306,203101,207787,212737,218071,223565,229287
3,5,Alabama,Barbour County,27325,27344,27172,26946,26768,26300,25828,25169,24887,24657,24589
4,7,Alabama,Bibb County,22858,22736,22657,22510,22541,22553,22590,22532,22300,22313,22136
5,9,Alabama,Blount County,57372,57561,57585,57630,57536,57535,57487,57801,57770,57840,57879
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3189,37,Wyoming,Sweetwater County,43580,44000,45032,45189,44996,44780,44319,43663,43188,42917,42673
3190,39,Wyoming,Teton County,21298,21422,21643,22335,22801,23083,23255,23383,23261,23385,23497
3191,41,Wyoming,Uinta County,21090,20901,21008,20969,20835,20777,20711,20449,20299,20196,20215
3192,43,Wyoming,Washakie County,8531,8451,8410,8417,8277,8282,8180,8013,7886,7824,7760
3193,45,Wyoming,Weston County,7198,7142,7075,7132,7134,7202,7228,6962,6895,6880,6743

In [67]:
#convert strings to numeric type for calculation of %
#convert strings to numeric type for calculation of %
county_df.loc[:,['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', \
                 'POPESTIMATE2014', 'POPESTIMATE2015', 'POPESTIMATE2016', 'POPESTIMATE2017', \
                 'POPESTIMATE2018', 'POPESTIMATE2019', 'POPESTIMATE2020']] = \
county_df[['POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', \
                 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015', \
                 'POPESTIMATE2016', 'POPESTIMATE2017', 'POPESTIMATE2018', \
                 'POPESTIMATE2019', 'POPESTIMATE2020']].apply(pd.to_numeric)
county_df.head()
county_df.dtypes

COUNTY              int64
STNAME             object
CTYNAME            object
POPESTIMATE2010     int64
POPESTIMATE2011     int64
POPESTIMATE2012     int64
POPESTIMATE2013     int64
POPESTIMATE2014     int64
POPESTIMATE2015     int64
POPESTIMATE2016     int64
POPESTIMATE2017     int64
POPESTIMATE2018     int64
POPESTIMATE2019     int64
POPESTIMATE2020     int64
dtype: object

In [69]:
county_df.loc[:,"Popestimate Yearly Change 2011(%)"] = ((county_df["POPESTIMATE2011"] / \
                                        county_df["POPESTIMATE2010"]) -1)*100

county_df.loc[:,"Popestimate Yearly Change 2012(%)"] = ((county_df["POPESTIMATE2012"] / \
                                        county_df["POPESTIMATE2011"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2013(%)"] = ((county_df["POPESTIMATE2013"] / \
                                        county_df["POPESTIMATE2012"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2014(%)"] = ((county_df["POPESTIMATE2014"] / \
                                        county_df["POPESTIMATE2013"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2015(%)"] = ((county_df["POPESTIMATE2015"] / \
                                        county_df["POPESTIMATE2014"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2016(%)"] = ((county_df["POPESTIMATE2016"] / \
                                        county_df["POPESTIMATE2015"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2017(%)"] = ((county_df["POPESTIMATE2017"] / \
                                        county_df["POPESTIMATE2016"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2018(%)"] = ((county_df["POPESTIMATE2018"] / \
                                        county_df["POPESTIMATE2017"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2019(%)"] = ((county_df["POPESTIMATE2019"] / \
                                        county_df["POPESTIMATE2018"]) -1)*100
county_df.loc[:,"Popestimate Yearly Change 2020(%)"] = ((county_df["POPESTIMATE2020"] / \
                                        county_df["POPESTIMATE2019"]) -1)*100
county_df.loc[:,"Popestimate 10-Year Change 2020(%)"] = ((county_df["POPESTIMATE2020"] / \
                                        county_df["POPESTIMATE2010"]) -1)*100

In [70]:
county_pct_change_df = county_df.loc[:, ['STNAME','CTYNAME','Popestimate Yearly Change 2011(%)', \
                                             'Popestimate Yearly Change 2012(%)', \
                                             'Popestimate Yearly Change 2013(%)', \
                                             'Popestimate Yearly Change 2014(%)',
                                             'Popestimate Yearly Change 2015(%)',
                                             'Popestimate Yearly Change 2016(%)',
                                             'Popestimate Yearly Change 2017(%)',
                                             'Popestimate Yearly Change 2018(%)',
                                             'Popestimate Yearly Change 2019(%)',
                                             'Popestimate Yearly Change 2020(%)',
                                             'Popestimate 10-Year Change 2020(%)']]
county_pct_change_df.head()

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
1,Alabama,Autauga County,0.854623,-0.468957,-0.405676,0.319652,-0.034595,0.726736,0.264005,0.153297,0.424973,0.674210,2.527346
2,Alabama,Baldwin County,1.888369,1.942341,2.510476,2.219738,1.904107,2.307226,2.382247,2.507321,2.519363,2.559435,25.210653
3,Alabama,Barbour County,0.069533,-0.629023,-0.831739,-0.660580,-1.748356,-1.794677,-2.551495,-1.120426,-0.924177,-0.275784,-10.012809
4,Alabama,Bibb County,-0.533730,-0.347467,-0.648806,0.137717,0.053236,0.164058,-0.256751,-1.029647,0.058296,-0.793260,-3.158632
5,Alabama,Blount County,0.329429,0.041695,0.078145,-0.163109,-0.001738,-0.083427,0.546210,-0.053632,0.121170,0.067427,0.883706

In [71]:
# Sort the data by 10-Year Change by County, Highest to Lowest
county_sorted_df = county_pct_change_df.sort_values(["Popestimate 10-Year Change 2020(%)"],
                                           ascending=False)

# Reset Index
county_sorted_df = county_sorted_df.reset_index(drop=True)
county_sorted_df.head()

,STNAME,CTYNAME,Popestimate Yearly Change 2011(%),Popestimate Yearly Change 2012(%),Popestimate Yearly Change 2013(%),Popestimate Yearly Change 2014(%),Popestimate Yearly Change 2015(%),Popestimate Yearly Change 2016(%),Popestimate Yearly Change 2017(%),Popestimate Yearly Change 2018(%),Popestimate Yearly Change 2019(%),Popestimate Yearly Change 2020(%),Popestimate 10-Year Change 2020(%)
0,North Dakota,McKenzie County,9.451029,13.835851,16.347478,18.310920,16.549968,-1.661855,0.880673,6.810853,10.728223,1.356563,137.710543
1,Texas,Loving County,13.095238,-9.473684,23.255814,-16.037736,33.707865,-1.680672,13.675214,12.030075,10.738255,9.696970,115.476190
2,North Dakota,Williams County,8.082865,9.575296,10.719492,8.584546,9.988808,-3.089403,-1.887068,6.120872,6.160009,2.118901,71.307158
3,Texas,Hays County,3.210278,3.214616,4.469556,5.019524,5.317053,5.135466,5.025882,3.753555,3.351755,4.759115,52.679554
4,Texas,Comal County,2.577051,2.469499,3.277718,3.880738,4.544570,4.297354,4.696893,5.336091,5.535317,5.354940,50.773481

In [72]:
# Print out the data for the county with the highest 10-Year Change
highest_10y_change = county_sorted_df.loc[0, :]
highest_10y_change

STNAME                                   North Dakota
CTYNAME                               McKenzie County
Popestimate Yearly Change 2011(%)            9.451029
Popestimate Yearly Change 2012(%)           13.835851
Popestimate Yearly Change 2013(%)           16.347478
Popestimate Yearly Change 2014(%)            18.31092
Popestimate Yearly Change 2015(%)           16.549968
Popestimate Yearly Change 2016(%)           -1.661855
Popestimate Yearly Change 2017(%)            0.880673
Popestimate Yearly Change 2018(%)            6.810853
Popestimate Yearly Change 2019(%)           10.728223
Popestimate Yearly Change 2020(%)            1.356563
Popestimate 10-Year Change 2020(%)         137.710543
Name: 0, dtype: object

In [73]:
# Print out the data for the county with the second highest 10-Year Change
highest_10y_change = county_sorted_df.loc[1, :]
highest_10y_change

STNAME                                        Texas
CTYNAME                               Loving County
Popestimate Yearly Change 2011(%)         13.095238
Popestimate Yearly Change 2012(%)         -9.473684
Popestimate Yearly Change 2013(%)         23.255814
Popestimate Yearly Change 2014(%)        -16.037736
Popestimate Yearly Change 2015(%)         33.707865
Popestimate Yearly Change 2016(%)         -1.680672
Popestimate Yearly Change 2017(%)         13.675214
Popestimate Yearly Change 2018(%)         12.030075
Popestimate Yearly Change 2019(%)         10.738255
Popestimate Yearly Change 2020(%)           9.69697
Popestimate 10-Year Change 2020(%)        115.47619
Name: 1, dtype: object

In [74]:
# Print out the data for the county with the lowest 10-Year Change
lowest_10y_change = county_sorted_df.loc[len(county_sorted_df)-1, :]
lowest_10y_change

STNAME                                        Illinois
CTYNAME                               Alexander County
Popestimate Yearly Change 2011(%)             -2.58379
Popestimate Yearly Change 2012(%)            -3.402978
Popestimate Yearly Change 2013(%)             -6.20386
Popestimate Yearly Change 2014(%)            -2.181718
Popestimate Yearly Change 2015(%)            -4.531338
Popestimate Yearly Change 2016(%)            -4.657696
Popestimate Yearly Change 2017(%)            -2.667494
Popestimate Yearly Change 2018(%)            -3.712556
Popestimate Yearly Change 2019(%)            -4.170114
Popestimate Yearly Change 2020(%)            -5.076843
Popestimate 10-Year Change 2020(%)          -33.004266
Name: 3142, dtype: object

In [75]:
# Print out the data for the county with the second lowest 10-Year Change
lowest_10y_change = county_sorted_df.loc[len(county_sorted_df)-2, :]
lowest_10y_change

STNAME                                        Texas
CTYNAME                               Concho County
Popestimate Yearly Change 2011(%)          0.487686
Popestimate Yearly Change 2012(%)         -0.946372
Popestimate Yearly Change 2013(%)          0.881921
Popestimate Yearly Change 2014(%)         -0.922778
Popestimate Yearly Change 2015(%)         -0.367647
Popestimate Yearly Change 2016(%)          1.697417
Popestimate Yearly Change 2017(%)        -34.663764
Popestimate Yearly Change 2018(%)         -0.814513
Popestimate Yearly Change 2019(%)          2.612915
Popestimate Yearly Change 2020(%)          2.837395
Popestimate 10-Year Change 2020(%)       -31.065594
Name: 3141, dtype: object